### ISSUE TITLE
Thanks, + some feedback

### ISSUE THREAD

**Issue by knbknb** [doom-goober/svg_style_attribute#1]
Thanks for your attempt to make Adobe-Illustrator SVGs more web-compatible.   
At least that was  the context I have tried your script successfully, with some tweaking.

Now I would like to give some feedback.

You should point out that people need to install *tinycss* (the old version, for python2) like this: 

`pip2 install tinycss`, that's what works for me.

About the next topic I am not sure, I'll desribe it anyway.

 Your tool also does not seem to check for compact style declarations such as

`.cls-1,.cls-2{fill:#3c3c3b;}`

which could be written as

```
.cls-1{fill:#3c3c3b;}
.cls-2{fill:#3c3c3b;}
```
I think your tool would probably pick up the correct defintions if the CSS was written in the latter form. The first form is too compact, I think.  
If this is correct, this should also be mentioned in the "Limitations" section of the README.

Maybe I have not fully understood the whole thing. At this point I am giving up. Enough time spent on this. I'll stick to Inkscape and avoid Adobe Illustrator where I can.

**Comment by doom-goober** [comment]
Thank you for the feedback! Unfortunately, I've abandoned this tool. Originally, I was working with Scour/Inkscape team to build this functionality into Inkscape. However, like you point out, CSS Style Declarations are very, very complicated and my solution doesn't come close to addressing all the corner cases. Scour is moving to use a proven CSS library which handles all the corner cases but Scour development is very, very slow too. :) Anyway, since there's an official effort and the tool works for me going from Illustrator -> Inkscape -> HTML5 (my work flow) I'm not going to develop this any further.

**Comment by knbknb** [comment]
Closed because script is no longer maintained.
